
language: php

php:
- '7.2'

services:
  - mysql

env:
  - SYMFONY_VERSION="4.1.*"

before-install:
- composer self-update

install:
  - composer install
  - cp .env.dist .env
  - php bin/console doctrine:database:create
  - php bin/console doctrine:schema:create
  - php bin/console doctrine:fixtures:load -n

script:
  - php bin/phpunit
